# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './GlaucomaGUI_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(840, 576)
        self.connections_gb = QtWidgets.QGroupBox(Form)
        self.connections_gb.setGeometry(QtCore.QRect(10, 10, 261, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.connections_gb.setFont(font)
        self.connections_gb.setObjectName("connections_gb")
        self.label = QtWidgets.QLabel(self.connections_gb)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.label.setObjectName("label")
        self.baseStationIp_cb = QtWidgets.QComboBox(self.connections_gb)
        self.baseStationIp_cb.setGeometry(QtCore.QRect(120, 20, 121, 21))
        self.baseStationIp_cb.setObjectName("baseStationIp_cb")
        self.baseStationIp_cb.addItem("")
        self.label_2 = QtWidgets.QLabel(self.connections_gb)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 81, 21))
        self.label_2.setObjectName("label_2")
        self.disconnectBaseStation_pb = QtWidgets.QPushButton(self.connections_gb)
        self.disconnectBaseStation_pb.setGeometry(QtCore.QRect(90, 90, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.disconnectBaseStation_pb.setFont(font)
        self.disconnectBaseStation_pb.setObjectName("disconnectBaseStation_pb")
        self.connectBaseStation_pb = QtWidgets.QPushButton(self.connections_gb)
        self.connectBaseStation_pb.setGeometry(QtCore.QRect(10, 90, 61, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.connectBaseStation_pb.setFont(font)
        self.connectBaseStation_pb.setObjectName("connectBaseStation_pb")
        self.addIp_pb = QtWidgets.QPushButton(self.connections_gb)
        self.addIp_pb.setGeometry(QtCore.QRect(190, 90, 61, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.addIp_pb.setFont(font)
        self.addIp_pb.setObjectName("addIp_pb")
        self.commFreq_le = QtWidgets.QLineEdit(self.connections_gb)
        self.commFreq_le.setGeometry(QtCore.QRect(120, 50, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.commFreq_le.setFont(font)
        self.commFreq_le.setAlignment(QtCore.Qt.AlignCenter)
        self.commFreq_le.setObjectName("commFreq_le")
        self.trialInfo_gb = QtWidgets.QGroupBox(Form)
        self.trialInfo_gb.setGeometry(QtCore.QRect(10, 140, 261, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trialInfo_gb.setFont(font)
        self.trialInfo_gb.setObjectName("trialInfo_gb")
        self.currentTime_te = QtWidgets.QTimeEdit(self.trialInfo_gb)
        self.currentTime_te.setGeometry(QtCore.QRect(140, 50, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.currentTime_te.setFont(font)
        self.currentTime_te.setObjectName("currentTime_te")
        self.currentDate_de = QtWidgets.QDateEdit(self.trialInfo_gb)
        self.currentDate_de.setGeometry(QtCore.QRect(140, 20, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.currentDate_de.setFont(font)
        self.currentDate_de.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 1, 1), QtCore.QTime(0, 0, 0)))
        self.currentDate_de.setObjectName("currentDate_de")
        self.label_3 = QtWidgets.QLabel(self.trialInfo_gb)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.trialInfo_gb)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.trialInfo_gb)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.trialLocation_cb = QtWidgets.QComboBox(self.trialInfo_gb)
        self.trialLocation_cb.setGeometry(QtCore.QRect(140, 80, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trialLocation_cb.setFont(font)
        self.trialLocation_cb.setObjectName("trialLocation_cb")
        self.trialLocation_cb.addItem("")
        self.trialLocation_cb.addItem("")
        self.trialLocation_cb.addItem("")
        self.trialLocation_cb.addItem("")
        self.label_6 = QtWidgets.QLabel(self.trialInfo_gb)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.patientId_le = QtWidgets.QLineEdit(self.trialInfo_gb)
        self.patientId_le.setGeometry(QtCore.QRect(80, 110, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.patientId_le.setFont(font)
        self.patientId_le.setObjectName("patientId_le")
        self.generatePatientId_pb = QtWidgets.QPushButton(self.trialInfo_gb)
        self.generatePatientId_pb.setGeometry(QtCore.QRect(20, 140, 231, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.generatePatientId_pb.setFont(font)
        self.generatePatientId_pb.setObjectName("generatePatientId_pb")
        self.addPatientInfo_pb = QtWidgets.QPushButton(self.trialInfo_gb)
        self.addPatientInfo_pb.setGeometry(QtCore.QRect(20, 170, 231, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addPatientInfo_pb.setFont(font)
        self.addPatientInfo_pb.setObjectName("addPatientInfo_pb")
        self.preTrialChecklist_gb = QtWidgets.QGroupBox(Form)
        self.preTrialChecklist_gb.setGeometry(QtCore.QRect(10, 340, 261, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.preTrialChecklist_gb.setFont(font)
        self.preTrialChecklist_gb.setObjectName("preTrialChecklist_gb")
        self.contactLensOrientation_checkBox = QtWidgets.QCheckBox(self.preTrialChecklist_gb)
        self.contactLensOrientation_checkBox.setGeometry(QtCore.QRect(20, 20, 211, 17))
        self.contactLensOrientation_checkBox.setObjectName("contactLensOrientation_checkBox")
        self.baseStationPower_checkBox = QtWidgets.QCheckBox(self.preTrialChecklist_gb)
        self.baseStationPower_checkBox.setGeometry(QtCore.QRect(20, 40, 171, 17))
        self.baseStationPower_checkBox.setObjectName("baseStationPower_checkBox")
        self.stimulatorPower_checkBox = QtWidgets.QCheckBox(self.preTrialChecklist_gb)
        self.stimulatorPower_checkBox.setGeometry(QtCore.QRect(20, 60, 171, 17))
        self.stimulatorPower_checkBox.setObjectName("stimulatorPower_checkBox")
        self.trialParameters_gb = QtWidgets.QGroupBox(Form)
        self.trialParameters_gb.setGeometry(QtCore.QRect(280, 10, 281, 241))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trialParameters_gb.setFont(font)
        self.trialParameters_gb.setObjectName("trialParameters_gb")
        self.label_8 = QtWidgets.QLabel(self.trialParameters_gb)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 101, 21))
        self.label_8.setObjectName("label_8")
        self.stimLocationLeftEye_rb = QtWidgets.QRadioButton(self.trialParameters_gb)
        self.stimLocationLeftEye_rb.setGeometry(QtCore.QRect(140, 110, 131, 20))
        self.stimLocationLeftEye_rb.setObjectName("stimLocationLeftEye_rb")
        self.stimLocationRightEye_rb = QtWidgets.QRadioButton(self.trialParameters_gb)
        self.stimLocationRightEye_rb.setGeometry(QtCore.QRect(140, 130, 141, 20))
        self.stimLocationRightEye_rb.setObjectName("stimLocationRightEye_rb")
        self.label_9 = QtWidgets.QLabel(self.trialParameters_gb)
        self.label_9.setGeometry(QtCore.QRect(10, 120, 121, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.trialParameters_gb)
        self.label_10.setGeometry(QtCore.QRect(10, 160, 121, 21))
        self.label_10.setObjectName("label_10")
        self.coil2CoilDist_le = QtWidgets.QLineEdit(self.trialParameters_gb)
        self.coil2CoilDist_le.setGeometry(QtCore.QRect(140, 160, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.coil2CoilDist_le.setFont(font)
        self.coil2CoilDist_le.setObjectName("coil2CoilDist_le")
        self.label_11 = QtWidgets.QLabel(self.trialParameters_gb)
        self.label_11.setGeometry(QtCore.QRect(240, 160, 31, 21))
        self.label_11.setObjectName("label_11")
        self.label_27 = QtWidgets.QLabel(self.trialParameters_gb)
        self.label_27.setGeometry(QtCore.QRect(10, 20, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.lensId_cb = QtWidgets.QComboBox(self.trialParameters_gb)
        self.lensId_cb.setGeometry(QtCore.QRect(120, 20, 151, 21))
        self.lensId_cb.setObjectName("lensId_cb")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.lensId_cb.addItem("")
        self.stimCoilName_cb = QtWidgets.QComboBox(self.trialParameters_gb)
        self.stimCoilName_cb.setGeometry(QtCore.QRect(120, 80, 151, 21))
        self.stimCoilName_cb.setObjectName("stimCoilName_cb")
        self.stimCoilName_cb.addItem("")
        self.stimCoilName_cb.addItem("")
        self.stimCoilName_cb.addItem("")
        self.stimCoilName_cb.addItem("")
        self.stimCoilName_cb.addItem("")
        self.stimCoilName_cb.addItem("")
        self.label_28 = QtWidgets.QLabel(self.trialParameters_gb)
        self.label_28.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.label_28.setObjectName("label_28")
        self.lensSequence_le = QtWidgets.QLineEdit(self.trialParameters_gb)
        self.lensSequence_le.setGeometry(QtCore.QRect(200, 50, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lensSequence_le.setFont(font)
        self.lensSequence_le.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lensSequence_le.setObjectName("lensSequence_le")
        self.addIopRecording_pb = QtWidgets.QPushButton(self.trialParameters_gb)
        self.addIopRecording_pb.setGeometry(QtCore.QRect(30, 192, 221, 31))
        self.addIopRecording_pb.setObjectName("addIopRecording_pb")
        self.stimParameters_gb = QtWidgets.QGroupBox(Form)
        self.stimParameters_gb.setGeometry(QtCore.QRect(280, 250, 281, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stimParameters_gb.setFont(font)
        self.stimParameters_gb.setObjectName("stimParameters_gb")
        self.label_12 = QtWidgets.QLabel(self.stimParameters_gb)
        self.label_12.setGeometry(QtCore.QRect(10, 80, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.stimPulseFrequency_le = QtWidgets.QLineEdit(self.stimParameters_gb)
        self.stimPulseFrequency_le.setGeometry(QtCore.QRect(145, 20, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stimPulseFrequency_le.setFont(font)
        self.stimPulseFrequency_le.setObjectName("stimPulseFrequency_le")
        self.label_13 = QtWidgets.QLabel(self.stimParameters_gb)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.stimPulseWidth_le = QtWidgets.QLineEdit(self.stimParameters_gb)
        self.stimPulseWidth_le.setGeometry(QtCore.QRect(145, 50, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stimPulseWidth_le.setFont(font)
        self.stimPulseWidth_le.setObjectName("stimPulseWidth_le")
        self.label_14 = QtWidgets.QLabel(self.stimParameters_gb)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.stimParameters_gb)
        self.label_15.setGeometry(QtCore.QRect(250, 80, 21, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.stimParameters_gb)
        self.label_16.setGeometry(QtCore.QRect(250, 20, 21, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.stimParameters_gb)
        self.label_17.setGeometry(QtCore.QRect(250, 50, 21, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.stimParameters_gb)
        self.label_18.setGeometry(QtCore.QRect(40, 133, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.stimParameters_gb)
        self.label_19.setGeometry(QtCore.QRect(70, 160, 31, 21))
        self.label_19.setObjectName("label_19")
        self.stimTimeHr_sb = QtWidgets.QSpinBox(self.stimParameters_gb)
        self.stimTimeHr_sb.setGeometry(QtCore.QRect(20, 160, 42, 22))
        self.stimTimeHr_sb.setObjectName("stimTimeHr_sb")
        self.label_20 = QtWidgets.QLabel(self.stimParameters_gb)
        self.label_20.setGeometry(QtCore.QRect(150, 160, 31, 21))
        self.label_20.setObjectName("label_20")
        self.stimTimeMin_sb = QtWidgets.QSpinBox(self.stimParameters_gb)
        self.stimTimeMin_sb.setGeometry(QtCore.QRect(100, 160, 42, 22))
        self.stimTimeMin_sb.setObjectName("stimTimeMin_sb")
        self.label_21 = QtWidgets.QLabel(self.stimParameters_gb)
        self.label_21.setGeometry(QtCore.QRect(230, 160, 31, 21))
        self.label_21.setObjectName("label_21")
        self.stimTimeSec_sb = QtWidgets.QSpinBox(self.stimParameters_gb)
        self.stimTimeSec_sb.setGeometry(QtCore.QRect(180, 160, 42, 22))
        self.stimTimeSec_sb.setObjectName("stimTimeSec_sb")
        self.beginTrial_pb = QtWidgets.QPushButton(self.stimParameters_gb)
        self.beginTrial_pb.setGeometry(QtCore.QRect(20, 200, 231, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.beginTrial_pb.setFont(font)
        self.beginTrial_pb.setObjectName("beginTrial_pb")
        self.resetTrial_pb = QtWidgets.QPushButton(self.stimParameters_gb)
        self.resetTrial_pb.setGeometry(QtCore.QRect(80, 230, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resetTrial_pb.setFont(font)
        self.resetTrial_pb.setObjectName("resetTrial_pb")
        self.label_29 = QtWidgets.QLabel(self.stimParameters_gb)
        self.label_29.setGeometry(QtCore.QRect(250, 110, 21, 21))
        self.label_29.setObjectName("label_29")
        self.label_trialStartTime = QtWidgets.QLabel(self.stimParameters_gb)
        self.label_trialStartTime.setGeometry(QtCore.QRect(46, 260, 191, 20))
        self.label_trialStartTime.setText("")
        self.label_trialStartTime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_trialStartTime.setObjectName("label_trialStartTime")
        self.stimPulseCurrentAmplitude_cb = QtWidgets.QComboBox(self.stimParameters_gb)
        self.stimPulseCurrentAmplitude_cb.setGeometry(QtCore.QRect(138, 80, 101, 22))
        self.stimPulseCurrentAmplitude_cb.setObjectName("stimPulseCurrentAmplitude_cb")
        self.stimPulseVoltageAmplitude_cb = QtWidgets.QComboBox(self.stimParameters_gb)
        self.stimPulseVoltageAmplitude_cb.setGeometry(QtCore.QRect(138, 110, 101, 22))
        self.stimPulseVoltageAmplitude_cb.setObjectName("stimPulseVoltageAmplitude_cb")
        self.postStimMeas_gb = QtWidgets.QGroupBox(Form)
        self.postStimMeas_gb.setGeometry(QtCore.QRect(570, 10, 261, 531))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.postStimMeas_gb.setFont(font)
        self.postStimMeas_gb.setObjectName("postStimMeas_gb")
        self.generateReport_pb = QtWidgets.QPushButton(self.postStimMeas_gb)
        self.generateReport_pb.setGeometry(QtCore.QRect(20, 500, 231, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.generateReport_pb.setFont(font)
        self.generateReport_pb.setObjectName("generateReport_pb")
        self.Iop_tableWidget = QtWidgets.QTableWidget(self.postStimMeas_gb)
        self.Iop_tableWidget.setGeometry(QtCore.QRect(10, 90, 241, 241))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.Iop_tableWidget.setFont(font)
        self.Iop_tableWidget.setAlternatingRowColors(True)
        self.Iop_tableWidget.setObjectName("Iop_tableWidget")
        self.Iop_tableWidget.setColumnCount(0)
        self.Iop_tableWidget.setRowCount(0)
        self.notes_pte = QtWidgets.QPlainTextEdit(self.postStimMeas_gb)
        self.notes_pte.setGeometry(QtCore.QRect(10, 360, 241, 131))
        self.notes_pte.setObjectName("notes_pte")
        self.label_30 = QtWidgets.QLabel(self.postStimMeas_gb)
        self.label_30.setGeometry(QtCore.QRect(80, 340, 101, 21))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.addIopMeasurement_pb = QtWidgets.QPushButton(self.postStimMeas_gb)
        self.addIopMeasurement_pb.setGeometry(QtCore.QRect(20, 30, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addIopMeasurement_pb.setFont(font)
        self.addIopMeasurement_pb.setObjectName("addIopMeasurement_pb")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(10, 550, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.version_label = QtWidgets.QLabel(Form)
        self.version_label.setGeometry(QtCore.QRect(400, 550, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.version_label.setFont(font)
        self.version_label.setObjectName("version_label")
        self.shutdownBaseStation_pb = QtWidgets.QPushButton(Form)
        self.shutdownBaseStation_pb.setGeometry(QtCore.QRect(590, 550, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shutdownBaseStation_pb.setFont(font)
        self.shutdownBaseStation_pb.setObjectName("shutdownBaseStation_pb")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.baseStationIp_cb, self.commFreq_le)
        Form.setTabOrder(self.commFreq_le, self.connectBaseStation_pb)
        Form.setTabOrder(self.connectBaseStation_pb, self.currentDate_de)
        Form.setTabOrder(self.currentDate_de, self.currentTime_te)
        Form.setTabOrder(self.currentTime_te, self.trialLocation_cb)
        Form.setTabOrder(self.trialLocation_cb, self.patientId_le)
        Form.setTabOrder(self.patientId_le, self.generatePatientId_pb)
        Form.setTabOrder(self.generatePatientId_pb, self.addPatientInfo_pb)
        Form.setTabOrder(self.addPatientInfo_pb, self.contactLensOrientation_checkBox)
        Form.setTabOrder(self.contactLensOrientation_checkBox, self.baseStationPower_checkBox)
        Form.setTabOrder(self.baseStationPower_checkBox, self.stimulatorPower_checkBox)
        Form.setTabOrder(self.stimulatorPower_checkBox, self.lensId_cb)
        Form.setTabOrder(self.lensId_cb, self.stimCoilName_cb)
        Form.setTabOrder(self.stimCoilName_cb, self.stimLocationLeftEye_rb)
        Form.setTabOrder(self.stimLocationLeftEye_rb, self.stimLocationRightEye_rb)
        Form.setTabOrder(self.stimLocationRightEye_rb, self.coil2CoilDist_le)
        Form.setTabOrder(self.coil2CoilDist_le, self.stimPulseFrequency_le)
        Form.setTabOrder(self.stimPulseFrequency_le, self.stimPulseWidth_le)
        Form.setTabOrder(self.stimPulseWidth_le, self.stimTimeHr_sb)
        Form.setTabOrder(self.stimTimeHr_sb, self.stimTimeMin_sb)
        Form.setTabOrder(self.stimTimeMin_sb, self.stimTimeSec_sb)
        Form.setTabOrder(self.stimTimeSec_sb, self.beginTrial_pb)
        Form.setTabOrder(self.beginTrial_pb, self.resetTrial_pb)
        Form.setTabOrder(self.resetTrial_pb, self.Iop_tableWidget)
        Form.setTabOrder(self.Iop_tableWidget, self.generateReport_pb)
        Form.setTabOrder(self.generateReport_pb, self.shutdownBaseStation_pb)
        Form.setTabOrder(self.shutdownBaseStation_pb, self.disconnectBaseStation_pb)
        Form.setTabOrder(self.disconnectBaseStation_pb, self.addIp_pb)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CID DataView"))
        self.connections_gb.setTitle(_translate("Form", "Connections"))
        self.label.setText(_translate("Form", "Base Station IP"))
        self.baseStationIp_cb.setItemText(0, _translate("Form", "192.168.42.1"))
        self.label_2.setText(_translate("Form", "Comm Freq"))
        self.disconnectBaseStation_pb.setText(_translate("Form", "Disconnect"))
        self.connectBaseStation_pb.setText(_translate("Form", "Connect"))
        self.addIp_pb.setText(_translate("Form", "Add IP"))
        self.commFreq_le.setText(_translate("Form", "60"))
        self.trialInfo_gb.setTitle(_translate("Form", "Trial Information"))
        self.label_3.setText(_translate("Form", "Date"))
        self.label_4.setText(_translate("Form", "Time"))
        self.label_5.setText(_translate("Form", "Trial Location"))
        self.trialLocation_cb.setItemText(0, _translate("Form", "Barcelona"))
        self.trialLocation_cb.setItemText(1, _translate("Form", "Case Western"))
        self.trialLocation_cb.setItemText(2, _translate("Form", "Madrid"))
        self.trialLocation_cb.setItemText(3, _translate("Form", "Purdue"))
        self.label_6.setText(_translate("Form", "Patient ID"))
        self.generatePatientId_pb.setText(_translate("Form", "Generate Patient ID"))
        self.addPatientInfo_pb.setText(_translate("Form", "Add Additonal Patient Information"))
        self.preTrialChecklist_gb.setTitle(_translate("Form", "Pre-Trial Checklist"))
        self.contactLensOrientation_checkBox.setText(_translate("Form", "Contact Lens Orientation"))
        self.baseStationPower_checkBox.setText(_translate("Form", "Base Station Power"))
        self.stimulatorPower_checkBox.setText(_translate("Form", "Stimulator Power"))
        self.trialParameters_gb.setTitle(_translate("Form", "Trial Parameters"))
        self.label_8.setText(_translate("Form", "Stimulator Coil"))
        self.stimLocationLeftEye_rb.setText(_translate("Form", "Patient\'s Left Eye"))
        self.stimLocationRightEye_rb.setText(_translate("Form", "Patient\'s Right Eye"))
        self.label_9.setText(_translate("Form", "Stimulation Location"))
        self.label_10.setText(_translate("Form", "Coil-Coil Distance"))
        self.label_11.setText(_translate("Form", "mm"))
        self.label_27.setText(_translate("Form", "Contact Lens ID"))
        self.lensId_cb.setItemText(0, _translate("Form", "S4a-1L"))
        self.lensId_cb.setItemText(1, _translate("Form", "S4a-2L"))
        self.lensId_cb.setItemText(2, _translate("Form", "S4b-1L"))
        self.lensId_cb.setItemText(3, _translate("Form", "S4b-2L"))
        self.lensId_cb.setItemText(4, _translate("Form", "S4c-1L"))
        self.lensId_cb.setItemText(5, _translate("Form", "S4c-2L"))
        self.lensId_cb.setItemText(6, _translate("Form", "S1-1L"))
        self.lensId_cb.setItemText(7, _translate("Form", "S1-2L"))
        self.lensId_cb.setItemText(8, _translate("Form", "S2-1L"))
        self.lensId_cb.setItemText(9, _translate("Form", "S2-2L"))
        self.lensId_cb.setItemText(10, _translate("Form", "S3-0L"))
        self.lensId_cb.setItemText(11, _translate("Form", "S3-1L"))
        self.lensId_cb.setItemText(12, _translate("Form", "S3-1L-B"))
        self.lensId_cb.setItemText(13, _translate("Form", "S3-2L"))
        self.lensId_cb.setItemText(14, _translate("Form", "R-2L"))
        self.lensId_cb.setItemText(15, _translate("Form", "No Lens"))
        self.stimCoilName_cb.setItemText(0, _translate("Form", "Coil A1"))
        self.stimCoilName_cb.setItemText(1, _translate("Form", "Coil A2"))
        self.stimCoilName_cb.setItemText(2, _translate("Form", "Coil A3"))
        self.stimCoilName_cb.setItemText(3, _translate("Form", "Coil MAG I"))
        self.stimCoilName_cb.setItemText(4, _translate("Form", "Coil MAG II"))
        self.stimCoilName_cb.setItemText(5, _translate("Form", "Coil June 2016"))
        self.label_28.setText(_translate("Form", "Lens Sequence #"))
        self.lensSequence_le.setText(_translate("Form", "0001"))
        self.addIopRecording_pb.setText(_translate("Form", "Add IOP Measurement"))
        self.stimParameters_gb.setTitle(_translate("Form", "Stimulus Parameters"))
        self.label_12.setText(_translate("Form", "Pulse Amplitude"))
        self.label_13.setText(_translate("Form", "Pulse Frequency"))
        self.label_14.setText(_translate("Form", "Pulse Width"))
        self.label_15.setText(_translate("Form", "uA"))
        self.label_16.setText(_translate("Form", "Hz"))
        self.label_17.setText(_translate("Form", "μS"))
        self.label_18.setText(_translate("Form", "Total Stimulation Time"))
        self.label_19.setText(_translate("Form", "Hr"))
        self.label_20.setText(_translate("Form", "Min"))
        self.label_21.setText(_translate("Form", "Sec"))
        self.beginTrial_pb.setText(_translate("Form", "Begin Trial"))
        self.resetTrial_pb.setText(_translate("Form", "Stop && Reset Trial"))
        self.label_29.setText(_translate("Form", "V"))
        self.postStimMeas_gb.setTitle(_translate("Form", "Post-Stimulation Measurements"))
        self.generateReport_pb.setText(_translate("Form", "Finish Trial && Generate Report"))
        self.label_30.setText(_translate("Form", "Notes"))
        self.addIopMeasurement_pb.setText(_translate("Form", "Add IOP Measurement"))
        self.label_26.setText(_translate("Form", "Center for Implantable Devices, Purdue University, West Lafayette    "))
        self.version_label.setText(_translate("Form", "V0.90"))
        self.shutdownBaseStation_pb.setText(_translate("Form", "Shutdown Base Station"))

