# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './GUI_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(901, 380)
        self.input_gb = QtWidgets.QGroupBox(Form)
        self.input_gb.setGeometry(QtCore.QRect(10, 10, 421, 211))
        self.input_gb.setObjectName("input_gb")
        self.fasta_gb = QtWidgets.QGroupBox(self.input_gb)
        self.fasta_gb.setGeometry(QtCore.QRect(10, 140, 401, 61))
        self.fasta_gb.setTitle("")
        self.fasta_gb.setObjectName("fasta_gb")
        self.fasta_le = QtWidgets.QLineEdit(self.fasta_gb)
        self.fasta_le.setGeometry(QtCore.QRect(30, 30, 311, 20))
        self.fasta_le.setObjectName("fasta_le")
        self.label_3 = QtWidgets.QLabel(self.fasta_gb)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 311, 16))
        self.label_3.setObjectName("label_3")
        self.fasta_pb = QtWidgets.QPushButton(self.fasta_gb)
        self.fasta_pb.setGeometry(QtCore.QRect(350, 30, 41, 21))
        self.fasta_pb.setObjectName("fasta_pb")
        self.gwas_gb = QtWidgets.QGroupBox(self.input_gb)
        self.gwas_gb.setGeometry(QtCore.QRect(10, 20, 401, 61))
        self.gwas_gb.setTitle("")
        self.gwas_gb.setObjectName("gwas_gb")
        self.label = QtWidgets.QLabel(self.gwas_gb)
        self.label.setGeometry(QtCore.QRect(10, 10, 261, 16))
        self.label.setObjectName("label")
        self.gwas_pb = QtWidgets.QPushButton(self.gwas_gb)
        self.gwas_pb.setGeometry(QtCore.QRect(350, 30, 41, 21))
        self.gwas_pb.setObjectName("gwas_pb")
        self.gwas_le = QtWidgets.QLineEdit(self.gwas_gb)
        self.gwas_le.setGeometry(QtCore.QRect(30, 30, 311, 20))
        self.gwas_le.setObjectName("gwas_le")
        self.gff_gb = QtWidgets.QGroupBox(self.input_gb)
        self.gff_gb.setGeometry(QtCore.QRect(10, 80, 401, 61))
        self.gff_gb.setTitle("")
        self.gff_gb.setObjectName("gff_gb")
        self.label_2 = QtWidgets.QLabel(self.gff_gb)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 331, 16))
        self.label_2.setObjectName("label_2")
        self.gff_le = QtWidgets.QLineEdit(self.gff_gb)
        self.gff_le.setGeometry(QtCore.QRect(30, 30, 311, 20))
        self.gff_le.setObjectName("gff_le")
        self.gff_pb = QtWidgets.QPushButton(self.gff_gb)
        self.gff_pb.setGeometry(QtCore.QRect(350, 30, 41, 21))
        self.gff_pb.setObjectName("gff_pb")
        self.parameters_gb = QtWidgets.QGroupBox(Form)
        self.parameters_gb.setGeometry(QtCore.QRect(10, 220, 421, 151))
        self.parameters_gb.setObjectName("parameters_gb")
        self.logp_label = QtWidgets.QLabel(self.parameters_gb)
        self.logp_label.setGeometry(QtCore.QRect(20, 30, 131, 16))
        self.logp_label.setObjectName("logp_label")
        self.logp_le = QtWidgets.QLineEdit(self.parameters_gb)
        self.logp_le.setGeometry(QtCore.QRect(310, 30, 81, 20))
        self.logp_le.setObjectName("logp_le")
        self.baseWidth_le = QtWidgets.QLineEdit(self.parameters_gb)
        self.baseWidth_le.setGeometry(QtCore.QRect(310, 60, 81, 20))
        self.baseWidth_le.setObjectName("baseWidth_le")
        self.baseWidth_label = QtWidgets.QLabel(self.parameters_gb)
        self.baseWidth_label.setGeometry(QtCore.QRect(20, 60, 281, 16))
        self.baseWidth_label.setObjectName("baseWidth_label")
        self.snpSearch_pb = QtWidgets.QPushButton(self.parameters_gb)
        self.snpSearch_pb.setGeometry(QtCore.QRect(110, 122, 191, 21))
        self.snpSearch_pb.setObjectName("snpSearch_pb")
        self.generateTree_cb = QtWidgets.QCheckBox(self.parameters_gb)
        self.generateTree_cb.setGeometry(QtCore.QRect(203, 90, 191, 20))
        self.generateTree_cb.setObjectName("generateTree_cb")
        self.search_gb = QtWidgets.QGroupBox(Form)
        self.search_gb.setGeometry(QtCore.QRect(440, 10, 461, 361))
        self.search_gb.setObjectName("search_gb")
        self.blast_gb = QtWidgets.QGroupBox(self.search_gb)
        self.blast_gb.setGeometry(QtCore.QRect(10, 50, 441, 151))
        self.blast_gb.setObjectName("blast_gb")
        self.numSave_label = QtWidgets.QLabel(self.blast_gb)
        self.numSave_label.setGeometry(QtCore.QRect(10, 20, 341, 16))
        self.numSave_label.setObjectName("numSave_label")
        self.numSave_le = QtWidgets.QLineEdit(self.blast_gb)
        self.numSave_le.setGeometry(QtCore.QRect(360, 20, 71, 21))
        self.numSave_le.setObjectName("numSave_le")
        self.searchType_gb = QtWidgets.QGroupBox(self.blast_gb)
        self.searchType_gb.setGeometry(QtCore.QRect(70, 50, 291, 61))
        self.searchType_gb.setTitle("")
        self.searchType_gb.setObjectName("searchType_gb")
        self.local_rb = QtWidgets.QRadioButton(self.searchType_gb)
        self.local_rb.setGeometry(QtCore.QRect(180, 30, 100, 20))
        self.local_rb.setObjectName("local_rb")
        self.remote_rb = QtWidgets.QRadioButton(self.searchType_gb)
        self.remote_rb.setGeometry(QtCore.QRect(180, 10, 100, 20))
        self.remote_rb.setObjectName("remote_rb")
        self.searchType_label = QtWidgets.QLabel(self.searchType_gb)
        self.searchType_label.setGeometry(QtCore.QRect(10, 20, 161, 16))
        self.searchType_label.setObjectName("searchType_label")
        self.outputFile_label = QtWidgets.QLabel(self.blast_gb)
        self.outputFile_label.setGeometry(QtCore.QRect(20, 120, 191, 16))
        self.outputFile_label.setObjectName("outputFile_label")
        self.blastOutputFileName_le = QtWidgets.QLineEdit(self.blast_gb)
        self.blastOutputFileName_le.setGeometry(QtCore.QRect(280, 120, 141, 20))
        self.blastOutputFileName_le.setObjectName("blastOutputFileName_le")
        self.doSearch_pb = QtWidgets.QPushButton(self.search_gb)
        self.doSearch_pb.setGeometry(QtCore.QRect(150, 290, 161, 32))
        self.doSearch_pb.setObjectName("doSearch_pb")
        self.blastEnable_cb = QtWidgets.QCheckBox(self.search_gb)
        self.blastEnable_cb.setGeometry(QtCore.QRect(100, 30, 101, 17))
        self.blastEnable_cb.setObjectName("blastEnable_cb")
        self.interproEnable_cb = QtWidgets.QCheckBox(self.search_gb)
        self.interproEnable_cb.setGeometry(QtCore.QRect(280, 30, 121, 17))
        self.interproEnable_cb.setObjectName("interproEnable_cb")
        self.interpro_gb = QtWidgets.QGroupBox(self.search_gb)
        self.interpro_gb.setGeometry(QtCore.QRect(10, 200, 441, 71))
        self.interpro_gb.setObjectName("interpro_gb")
        self.interproOutputFileName_le = QtWidgets.QLineEdit(self.interpro_gb)
        self.interproOutputFileName_le.setGeometry(QtCore.QRect(280, 30, 141, 20))
        self.interproOutputFileName_le.setObjectName("interproOutputFileName_le")
        self.outputFile2_label = QtWidgets.QLabel(self.interpro_gb)
        self.outputFile2_label.setGeometry(QtCore.QRect(20, 30, 191, 16))
        self.outputFile2_label.setObjectName("outputFile2_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BIOL 595 Project"))
        self.input_gb.setTitle(_translate("Form", "Input"))
        self.label_3.setText(_translate("Form", "Please select your FastA file for the organism."))
        self.fasta_pb.setText(_translate("Form", "..."))
        self.label.setText(_translate("Form", "Please select your GWAS file."))
        self.gwas_pb.setText(_translate("Form", "..."))
        self.label_2.setText(_translate("Form", "Please select your .gff file for the selected organism."))
        self.gff_pb.setText(_translate("Form", "..."))
        self.parameters_gb.setTitle(_translate("Form", "SNP Search Parameters"))
        self.logp_label.setText(_translate("Form", "Cutoff -log(p) value:"))
        self.logp_le.setText(_translate("Form", "3.0"))
        self.baseWidth_le.setText(_translate("Form", "200000"))
        self.baseWidth_label.setText(_translate("Form", "Number of base pairs surrounding each SNP:"))
        self.snpSearch_pb.setText(_translate("Form", "Find Significant SNPs"))
        self.generateTree_cb.setText(_translate("Form", "Generate Phylogenic Tree"))
        self.search_gb.setTitle(_translate("Form", "Database Search"))
        self.blast_gb.setTitle(_translate("Form", "Blast"))
        self.numSave_label.setText(_translate("Form", "How many results should be saved for each sequence?"))
        self.numSave_le.setText(_translate("Form", "5"))
        self.local_rb.setText(_translate("Form", "Local"))
        self.remote_rb.setText(_translate("Form", "Remote"))
        self.searchType_label.setText(_translate("Form", "Local or remote search?"))
        self.outputFile_label.setText(_translate("Form", "Blast output file name:"))
        self.blastOutputFileName_le.setText(_translate("Form", "blastOut.txt"))
        self.doSearch_pb.setText(_translate("Form", "Perform Search"))
        self.blastEnable_cb.setText(_translate("Form", "BLastx"))
        self.interproEnable_cb.setText(_translate("Form", "InterPro"))
        self.interpro_gb.setTitle(_translate("Form", "InterPro"))
        self.interproOutputFileName_le.setText(_translate("Form", "interProOut.txt"))
        self.outputFile2_label.setText(_translate("Form", "InterPro output file name:"))

